# Generated by Django 3.2 on 2021-04-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=10, verbose_name='Valor total'),
            preserve_default=False,
        ),
    ]
