# Generated by Django 3.2 on 2021-04-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_venda_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
    ]
