# Generated by Django 3.2 on 2021-04-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_remove_venda_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='falecido',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data_cadastro',
        ),
    ]
