# Generated by Django 3.2 on 2021-04-30 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_auto_20210429_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falecido',
            name='rg',
        ),
    ]
